CREATE TABLE grocery(id INTEGER PRIMARY KEY,TYPE REAL, name TEXT, quantity INTEGER, price INTEGER);

INSERT INTO GROCERY VALUES (1, "APPLES","FUJI", 20, 1.50);
INSERT INTO GROCERY VALUES (2, "ORANGES","NAVAL", 35, 2.00);
INSERT INTO GROCERY VALUES (3, "PEACHES","YELLOW", 20, 2.50);
INSERT INTO GROCERY VALUES (4, "PIES", "CHERRY", 7, 10.99);
INSERT INTO GROCERY VALUES (5, "ONIONS","WHITE", 29, .99);

SELECT * FROM GROCERY ORDER BY PRICE;
SELECT * FROM GROCERY ORDER BY TYPE;
SELECT * FROM GROCERY ORDER BY QUANTITY;
